# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: popularity 0.2.1 ruby lib

Gem::Specification.new do |s|
  s.name = "popularity"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jeff Keen"]
  s.date = "2015-05-22"
  s.description = "Supports Facebook, Twitter, Pinterest, Reddit (Links, Posts, and Comments), Github, Soundcloud, Medium, and Rubygems"
  s.email = "jeff@keen.me"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/.DS_Store",
    "lib/popularity.rb",
    "lib/popularity/crawler.rb",
    "lib/popularity/networks/facebook.rb",
    "lib/popularity/networks/github.rb",
    "lib/popularity/networks/google_plus.rb",
    "lib/popularity/networks/medium.rb",
    "lib/popularity/networks/pinterest.rb",
    "lib/popularity/networks/reddit_comment.rb",
    "lib/popularity/networks/reddit_post.rb",
    "lib/popularity/networks/reddit_share.rb",
    "lib/popularity/networks/rubygems.rb",
    "lib/popularity/networks/soundcloud.rb",
    "lib/popularity/networks/twitter.rb",
    "lib/popularity/results_container.rb",
    "lib/popularity/rubygems.rb",
    "lib/popularity/search.rb",
    "popularity.gemspec",
    "spec/cassettes/facebook.yml",
    "spec/cassettes/github-valid.yml",
    "spec/cassettes/google_plus.yml",
    "spec/cassettes/medium-valid.yml",
    "spec/cassettes/pinterest.yml",
    "spec/cassettes/reddit-comment.yml",
    "spec/cassettes/reddit-post.yml",
    "spec/cassettes/reddit.yml",
    "spec/cassettes/result-container-test.yml",
    "spec/cassettes/rubygems-valid.yml",
    "spec/cassettes/search-multi.yml",
    "spec/cassettes/search.yml",
    "spec/cassettes/soundcloud-valid.yml",
    "spec/cassettes/twitter.yml",
    "spec/cassettes/unknown-reddit-post.yml",
    "spec/facebook_spec.rb",
    "spec/github_spec.rb",
    "spec/google_plus_spec.rb",
    "spec/medium_spec.rb",
    "spec/pinterest_spec.rb",
    "spec/reddit_comment_spec.rb",
    "spec/reddit_post_spec.rb",
    "spec/reddit_spec.rb",
    "spec/results_container_spec.rb",
    "spec/rubygems_spec.rb",
    "spec/search_spec.rb",
    "spec/soundcloud_spec.rb",
    "spec/spec_helper.rb",
    "spec/twitter_spec.rb"
  ]
  s.homepage = "http://github.com/jkeen/popularity"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Popularity searches social networks a url and returns the metrics."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<open_uri_redirections>, ["~> 0"])
      s.add_runtime_dependency(%q<json>, ["~> 1.8"])
      s.add_runtime_dependency(%q<unirest>, ["~> 1"])
      s.add_runtime_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0"])
      s.add_development_dependency(%q<awesome_print>, ["~> 1.6"])
    else
      s.add_dependency(%q<open_uri_redirections>, ["~> 0"])
      s.add_dependency(%q<json>, ["~> 1.8"])
      s.add_dependency(%q<unirest>, ["~> 1"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<simplecov>, ["~> 0"])
      s.add_dependency(%q<awesome_print>, ["~> 1.6"])
    end
  else
    s.add_dependency(%q<open_uri_redirections>, ["~> 0"])
    s.add_dependency(%q<json>, ["~> 1.8"])
    s.add_dependency(%q<unirest>, ["~> 1"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<simplecov>, ["~> 0"])
    s.add_dependency(%q<awesome_print>, ["~> 1.6"])
  end
end

